# Site settings
title: A blog by jjungoori
description: by high school freshmen
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
permalink: /posts/:title/

# User settings
username: jjungoori
user_description: learning!
user_title: Student developer
email: junwoolee0813@gmail.com
twitter_username: "nope"
github_username:  jjungoori
gplus_username:  "nope"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
